version: "3"

services:
  neo4j:
    container_name: neo4j
    image: neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $PWD/neo4j:/data/db
    environment:
      NEO4J_AUTH: neo4j/setpassword
      NEO4J_dbms_memory_pagecache_size: 5G
